"""
Django settings for Nelsaproject project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Environment-first secret key; dev-safe fallback only when env var is not set.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'dev-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
# Use environment variable to control DEBUG setting
# Convert string 'False' to boolean False
DEBUG_ENV = os.environ.get('DJANGO_DEBUG', 'False')
DEBUG = DEBUG_ENV.lower() in ('true', '1', 'yes', 'on')
DEPLOYMENT_ENV = os.environ.get('DEPLOYMENT_ENV', 'development').strip().lower()

# Configure ALLOWED_HOSTS from environment variable or use Render-safe defaults
ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_ENV:
    # Split comma-separated hosts and strip whitespace
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',') if host.strip()]
else:
    # Defaults that work locally and on Render
    ALLOWED_HOSTS = ['.onrender.com', 'localhost', '127.0.0.1', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'NelsaApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # must be after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Nelsaproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR / 'NelsaApp' / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Nelsaproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration (environment-driven)
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes', 'on')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@moghamo.local')

# Branding / public URLs (used in emails, QR absolute links — set via environment in production)
COMPANY_NAME = os.environ.get('COMPANY_NAME', 'MOGHAMO EXPRESS')
COMPANY_SUPPORT_EMAIL = os.environ.get('COMPANY_SUPPORT_EMAIL', DEFAULT_FROM_EMAIL)
COMPANY_SUPPORT_PHONE = os.environ.get('COMPANY_SUPPORT_PHONE', '+237675315422')
PUBLIC_SITE_URL = os.environ.get('PUBLIC_SITE_URL', 'http://127.0.0.1:8000').rstrip('/')

# Payment webhook security
PAYMENT_WEBHOOK_SECRET = os.environ.get('PAYMENT_WEBHOOK_SECRET', '')
# Optional HMAC of raw body (hex) — header X-Webhook-Body-Signature
PAYMENT_WEBHOOK_HMAC_SECRET = os.environ.get('PAYMENT_WEBHOOK_HMAC_SECRET', '')

# Ops alerts (comma-separated emails) + webhook failure emails
ALERT_EMAIL_RECIPIENTS = [
    e.strip()
    for e in os.environ.get('ALERT_EMAIL_RECIPIENTS', '').split(',')
    if e.strip()
]
ALERT_ON_WEBHOOK_FAILURE = os.environ.get('ALERT_ON_WEBHOOK_FAILURE', 'False').lower() in (
    'true',
    '1',
    'yes',
    'on',
)

# Internal JSON metrics (token in X-Metrics-Token or ?token=); if unset, staff with webhook perm may access
METRICS_AUTH_TOKEN = os.environ.get('METRICS_AUTH_TOKEN', '')

# Signed QR ticket tokens (optional separate secret; defaults to SECRET_KEY if unset)
TICKET_SIGNING_SECRET = os.environ.get('TICKET_SIGNING_SECRET', '')
TICKET_MAX_AGE_SECONDS = int(os.environ.get('TICKET_MAX_AGE_SECONDS', str(120 * 24 * 3600)))

# SMS Configuration (all live credentials from environment — no API secrets in code)
SMS_ENABLED = os.environ.get('SMS_ENABLED', 'True').lower() in ('true', '1', 'yes', 'on')
SMS_PROVIDER = os.environ.get('SMS_PROVIDER', 'twilio')  # 'mock', 'twilio', or 'africas_talking' (AT not implemented)
SMS_FROM_NUMBER = os.environ.get('SMS_FROM_NUMBER', '')

# Twilio (required in production when SMS_ENABLED and SMS_PROVIDER=twilio — see _validate_required_env)
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', '')

# Africa's Talking Configuration (if using Africa's Talking)
AFRICASTALKING_API_KEY = os.environ.get('AFRICASTALKING_API_KEY', '')
AFRICASTALKING_USERNAME = os.environ.get('AFRICASTALKING_USERNAME', '')
AFRICASTALKING_SENDER_ID = os.environ.get('AFRICASTALKING_SENDER_ID', 'NelsaNdo')


def _validate_required_env():
    """
    Enforce critical env vars in production-like environments.
    Keeps local development flexible while protecting real deployments.
    """
    if DEPLOYMENT_ENV not in ('production', 'staging'):
        return

    required = {
        'DJANGO_SECRET_KEY': os.environ.get('DJANGO_SECRET_KEY', ''),
        'EMAIL_HOST_USER': EMAIL_HOST_USER,
        'EMAIL_HOST_PASSWORD': EMAIL_HOST_PASSWORD,
        'DEFAULT_FROM_EMAIL': DEFAULT_FROM_EMAIL,
        'PAYMENT_WEBHOOK_SECRET': PAYMENT_WEBHOOK_SECRET,
        'PUBLIC_SITE_URL': PUBLIC_SITE_URL,
        'COMPANY_SUPPORT_PHONE': COMPANY_SUPPORT_PHONE,
    }

    if SMS_ENABLED and SMS_PROVIDER == 'twilio':
        required.update(
            {
                'TWILIO_ACCOUNT_SID': TWILIO_ACCOUNT_SID,
                'TWILIO_AUTH_TOKEN': TWILIO_AUTH_TOKEN,
                'TWILIO_PHONE_NUMBER': TWILIO_PHONE_NUMBER,
            }
        )

    missing = [name for name, value in required.items() if not str(value).strip()]
    if missing:
        raise ImproperlyConfigured(
            f"Missing required environment variable(s) for {DEPLOYMENT_ENV}: {', '.join(missing)}"
        )

    if SECRET_KEY == 'dev-only-change-me':
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set to a strong secret in production/staging."
        )


_validate_required_env()

# For development/testing, you can use console backend instead:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Additional settings to prevent 400 errors
# CSRF_TRUSTED_ORIGINS can be set from environment variable or use defaults
CSRF_TRUSTED_ORIGINS_ENV = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if CSRF_TRUSTED_ORIGINS_ENV:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS_ENV.split(',')]
else:
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'https://*.onrender.com',
    ]
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_HTTPONLY = False

# Security Settings for Production
if not DEBUG:
    # Security settings for production
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_REDIRECT_EXEMPT = []
    # Disable SSL redirect for development
    SECURE_SSL_REDIRECT = False
    # Disable secure cookies for development
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    X_FRAME_OPTIONS = 'DENY'
    
    # Logging configuration for production
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'file': {
                'level': 'INFO',
                'class': 'logging.FileHandler',
                'filename': str(BASE_DIR / 'logs' / 'django.log'),
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file'],
                'level': 'INFO',
                'propagate': True,
            },
            'nelsa.audit': {
                'handlers': ['file'],
                'level': 'INFO',
                'propagate': False,
            },
            'nelsa.ops': {
                'handlers': ['file'],
                'level': 'WARNING',
                'propagate': False,
            },
        },
    }
else:
    # Development logging
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'loggers': {
            'nelsa.audit': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'nelsa.ops': {
                'handlers': ['console'],
                'level': 'WARNING',
                'propagate': False,
            },
        },
    }
