# Generated by Django 5.1.7 on 2026-03-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NelsaApp', '0021_paymentwebhooknonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinggroup',
            name='confirmation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='customer_cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='customer_cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='customer_notification_status',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('PROCESSING', 'Notifications processing'), ('SMS_DELIVERED', 'SMS delivered'), ('EMAIL_DELIVERED', 'Email delivered'), ('SMS_AND_EMAIL', 'SMS and email delivered'), ('SMS_FAILED_EMAIL_DELIVERED', 'SMS failed; email delivered'), ('SMS_FAILED_EMAIL_FAILED', 'SMS failed; email failed'), ('DELIVERY_FAILED', 'Delivery failed — contact support')], db_index=True, default='N/A', max_length=40),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='customer_refund_requested',
            field=models.BooleanField(default=False, help_text='True when the passenger submitted a refund request via self-service.'),
        ),
    ]
